### ISSUE TITLE
Add support for expansion without ":"

### ISSUE THREAD

**Issue by luccamordente** [billymoon/Stylus-Snippets#1]
Wouldn't be nice to have a setting to tell whether to expanded with ":" or not?

Today expansions happen like this:

```
m0 ⇢ 
margin: 0
```

I personally don't like the ":", so all code I write is like this:

```
margin 0
```

I just started using Sublime Text and would appreciate this feature.
Thanks

**Comment by yustnip** [comment]
Would like the same.

**Comment by yukulele** [comment]
Install <a href="https://packagecontrol.io/packages/Hayaku%20-%20tools%20for%20writing%20CSS%20faster">Hayaku</a> fix it

examples:
- `m` -> `margin`
- `m10` -> `margin 10px`
